# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [60]:
import pandas as pd
from sklearn.model_selection import train_test_split  
from sklearn.linear_model import LinearRegression, LogisticRegression, PoissonRegressor, SGDClassifier
from sklearn.metrics import r2_score, mean_squared_error as mse, mean_absolute_error as mae, accuracy_score, balanced_accuracy_score as bas, precision_score, recall_score, f1_score, confusion_matrix

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [5]:
lr_d = LinearRegression()
lr_data = lr_d.fit(X_train, y_train)
y_pred = lr_data.predict(X_train)
y_test_pred = lr_data.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [6]:
r2_score_train = r2_score(y_train, y_pred)
r2_score_test = r2_score(y_test, y_test_pred)

In [7]:
r2_score_train

0.7454319061116375

In [8]:
r2_score_test

0.6846380914522745

## 4. Calculate and print mean squared error for both the training and the testing set.

In [9]:
mse_train= mse(y_train, y_pred)
mse_test = mse(y_test, y_test_pred)

In [10]:
mse_train

23.00720120332114

In [11]:
mse_test

18.29280454203947

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [12]:
mae_train = mae(y_train, y_pred)
mae_test = mae(y_test, y_test_pred)

In [13]:
mae_train

3.365433584210996

In [14]:
mae_test

3.295789948279104

## Classification Model Evaluation

In [15]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [16]:
data.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
class                  int32
dtype: object

In [17]:
data.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
class                0
dtype: int64

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [19]:
log_r = LogisticRegression(max_iter=10000)
log_data = log_r.fit(X_train, y_train)
y_log_pred = log_data.predict(X_train)
y_log_pred_test = log_data.predict(X_test)

C:\Users\magar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [20]:
as_train = accuracy_score(y_train, y_log_pred)
as_test = accuracy_score(y_test, y_log_pred_test)

In [21]:
as_train

0.9833333333333333

In [22]:
as_test

0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [23]:
bas_train = bas(y_train, y_log_pred)
bas_test = bas(y_test, y_log_pred_test)

In [24]:
bas_train

0.981981981981982

In [25]:
bas_test

0.9743589743589745

## 10. Calculate and print the precision score for both the training and the testing set.

In [26]:
pr_train = precision_score(y_train, y_log_pred, average="macro")
pr_test = precision_score(y_test, y_log_pred_test, average="macro")

In [27]:
pr_train

0.9848484848484849

In [28]:
pr_test

0.9629629629629629

## 11. Calculate and print the recall score for both the training and the testing set.

In [29]:
re_train = recall_score(y_train, y_log_pred, average="macro")
re_test = recall_score(y_test, y_log_pred_test, average="macro")

In [30]:
re_train

0.981981981981982

In [31]:
re_test

0.9743589743589745

## 12. Calculate and print the F1 score for both the training and the testing set.

In [32]:
f1_train = f1_score(y_train, y_log_pred, average="macro")
f1_test = f1_score(y_test, y_log_pred_test, average="macro")

In [33]:
f1_train

0.9829888027562447

In [34]:
f1_test

0.9670588235294119

## 13. Generate confusion matrices for both the training and the testing set.

In [35]:
confusion_matrix(y_true = y_train, y_pred = y_log_pred)

array([[41,  0,  0],
       [ 0, 35,  2],
       [ 0,  0, 42]], dtype=int64)

In [36]:
confusion_matrix(y_true= y_test, y_pred = y_log_pred_test)

array([[ 9,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  8]], dtype=int64)

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

### Regression Model Evaluation

In [37]:
data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [39]:
log_data = PoissonRegressor(max_iter=10000)
log_d = log_data.fit(X=X_train, y=y_train)
pred_log_d = log_d.predict(X_train)
pred_log_d_test = log_d.predict(X_test)

C:\Users\magar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [44]:
r2_train = r2_score(y_train, pred_log_d)
r2_test = r2_score(y_test, pred_log_d_test)

In [45]:
r2_train

0.8064288933206176

In [46]:
r2_test

0.7239718109223592

In [51]:
mse_train = mse(y_train, pred_log_d)
mse_test = mse(y_test, pred_log_d_test)

In [52]:
mse_train

15.41930518198463

In [53]:
mse_test

28.24186714564668

In [54]:
mae_train = mae(y_train, pred_log_d)
mae_test = mae(y_test, pred_log_d_test)

In [55]:
mae_train

2.754928164479281

In [56]:
mae_test

3.192957137651963

### Classification Model Evaluation

In [57]:
data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

In [58]:
data.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
MEDV                   int32
dtype: object

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [71]:
sgd = SGDClassifier()
sgd_data = sgd.fit(X = X_train, y = np.array(y_train))
sgd_pred  = sgd_data.predict(X_train)
sgd_pred_test  = sgd_data.predict(X_test)

C:\Users\magar\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [72]:
as_train = accuracy_score(y_train, sgd_pred)
as_test = accuracy_score(y_test, sgd_pred_test)

In [73]:
as_train

0.95

In [74]:
as_test

0.9

In [75]:
bas_train = bas(y_train, sgd_pred)
bas_test = bas(y_test, sgd_pred_test)

In [76]:
bas_train

0.9472972972972973

In [77]:
bas_test

0.923076923076923

In [80]:
pr_train = precision_score(y_train, sgd_pred, average="macro")
pr_test = precision_score(y_test, sgd_pred_test, average="macro")

In [81]:
pr_train

0.9508742891095833

In [82]:
pr_test

0.923076923076923

In [83]:
re_train = recall_score(y_train, sgd_pred, average="macro")
re_test = recall_score(y_test, sgd_pred_test, average="macro")

In [84]:
re_train

0.9472972972972973

In [85]:
re_test

0.923076923076923

In [86]:
f1_train = f1_score(y_train, sgd_pred, average="macro")
f1_test = f1_score(y_test, sgd_pred_test, average="macro")

In [87]:
f1_train

0.948304160069284

In [88]:
f1_test

0.9130434782608696

In [91]:
confusion_matrix(y_true = y_train, y_pred = sgd_pred)

array([[43,  0,  0],
       [ 1, 38,  1],
       [ 0,  4, 33]], dtype=int64)

In [92]:
confusion_matrix(y_true= y_test, y_pred = sgd_pred_test)

array([[ 7,  0,  0],
       [ 0, 10,  0],
       [ 0,  3, 10]], dtype=int64)